### ISSUE TITLE
Add support for subreddits

### ISSUE THREAD

**Issue by tobidalhof** [tobidalhof/sanersocialmedia#3]

**Comment by daedroza** [comment]
There is a pull request already for this, possible cherry-pick? https://github.com/jordwest/news-feed-eradicator/pull/163

**Comment by tobidalhof** [comment]
> There is a pull request already for this, possible cherry-pick? [jordwest/news-feed-eradicator#163](https://github.com/jordwest/news-feed-eradicator/pull/163)

Looking into it during the weekend, should be easy to implement. Cherry picking is not possible because this project is not a fork of News Feed Eradicator

**Comment by tobidalhof** [comment]
This feature was added to `v1.2.0`. It should be available in the Chrome Web Store during next week.
